kind: pipeline
type: docker
name: rancher-deploy

globals:
  - &docker_creds
    DOCKER_ID:
      from_secrets: DOCKER_ID
    DOCKER_PASSWORD:
      from_secrets: DOCKER_PASSWORD
    RANCHER_ACCESS_KEY:
      from_secrets: RANCHER_ACCESS_KEY
    RANCHER_SECRET_KEY:
      from_secrets: RANCHER_SECRET_KEY

steps:
  - name: rancher
    image: pelotech/drone-rancher
    settings:
      url: http://37.46.83.196:8080/
      access_key: $RANCHER_ACCESS_KEY
      secret_key: $RANCHER_SECRET_KEY
      service: docker-multi/worker
      docker_image: registry.gitlab.com/radym/multi-docker/multi-worker
      start_first: false
      confirm: true
      timeout: 180
    environment:
      DOCKER_ID:
        from_secrets: DOCKER_ID
      DOCKER_PASSWORD:
        from_secrets: DOCKER_PASSWORD
      RANCHER_ACCESS_KEY:
        from_secrets: RANCHER_ACCESS_KEY
      RANCHER_SECRET_KEY:
        from_secrets: RANCHER_SECRET_KEY
#      <<: *docker_creds