kind: pipeline
type: docker
name: multi-docker

globals:
  - &docker_creds
    DOCKER_ID:
      from_secrets: DOCKER_ID
    DOCKER_PASSWORD:
      from_secrets: DOCKER_PASSWORD

steps:
  - name: build
    image: docker:dind
    commands:
    - sleep 60
    - docker build -t registry.gitlab.com/radym/multi-client ./client
    environment:
      <<: *docker_creds
    when:
      branch: master
#  commands:
#    - docker build -t registry.gitlab.com/radym/multi-client ./client
#    - docker build -t registry.gitlab.com/radym/multi-nginx ./nginx
#    - docker build -t registry.gitlab.com/radym/multi-server ./server
#    - docker build -t registry.gitlab.com/radym/multi-worker ./worker
    # Log in to the docker CLI
#    - echo "$DOCKER_PASSWORD" | docker login registry.gitlab.com -u "$DOCKER_ID" --password-stdin
    # Take images and push them to Docker Hub
#    - docker push registry.gitlab.com/radym/multi-client:latest
#    - docker push registry.gitlab.com/radym/multi-nginx:latest
#    - docker push registry.gitlab.com/radym/multi-server:latest
#    - docker push registry.gitlab.com/radym/multi-worker:latest