image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - build
 # - test
  - deploy

default:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    # Build images
#    - docker build -t registry.gitlab.com/radym/multi-docker/multi-client ./client
    - docker build -t registry.gitlab.com/radym/multi-docker/multi-nginx ./nginx
#    - docker build -t registry.gitlab.com/radym/multi-docker/multi-server ./server
#    - docker build -t registry.gitlab.com/radym/multi-docker/multi-worker ./worker
    # Push images into repository
#    - docker push registry.gitlab.com/radym/multi-docker/multi-client:latest
    - docker push registry.gitlab.com/radym/multi-docker/multi-nginx:latest
#    - docker push registry.gitlab.com/radym/multi-docker/multi-server:latest
#    - docker push registry.gitlab.com/radym/multi-docker/multi-worker:latest

#test:
#  stage: test
#  script:
#    - docker build -t radym/react-test -f ./client/Dockerfile.dev ./client
#    - docker run -e CI=true radym/react-test npm test -- --coverage

deploy:
  stage: deploy
  inherit:
    default: false
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image
  image:
    name: 512k/rancher-cli:0.6
    entrypoint: [""]
  services: []
  variables:
    RANCHER_URL: $RANCHER_URL 
    RANCHER_ACCESS_KEY: $RANCHER_ACCESS_KEY
    RANCHER_SECRET_KEY: $RANCHER_SECRET_KEY
    RANCHER_ENVIRONMENT: $RANCHER_ENVIRONMENT
  script:
    - /bin/sh
    - cd
    - rancher export docker-multi
    - cd docker-multi
  #  - rancher stop docker-multi/nginx
  #  - rancher start docker-multi/nginx
    - rancher up -s docker-multi -d -p -c --force-upgrade


