sudo: required
services:
  - docker

before_install:
  - docker build -t radym/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true radym/react-test npm test -- --coverage

after_success:
  - docker build -t radym/multi-client ./client
  - docker build -t radym/multi-nginx ./nginx
  - docker build -t radym/multi-server ./server
  - docker build -t radym/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to Docker Hub
  - docker push radym/multi-client
  - docker push radym/multi-nginx
  - docker push radym/multi-server
  - docker push radym/multi-worker